---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: building
  namespace: dev
  labels:
    app: building
spec:
  selector:
    matchLabels:
      app: building
  template:
    metadata:
      labels:
        app: building
    spec:
      containers:
        - name: building
          image: registry.ngaxavilabs.com/devops/building
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_PREFIX
              value: dev
            - name: KAFKA_HOST
              value: kafka.kafka
            - name: KAFKA_PORT
              value: '9094'
      imagePullSecrets:
        - name: registry-devops

---
apiVersion: v1
kind: Service
metadata:
  name: building
  namespace: dev
  labels:
    app: building
spec:
  selector:
    app: building
  ports:
    - port: 3000
      name: building-port
      targetPort: 3000
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: building
  namespace: dev
  labels:
    app: building
stringData:
  MONGO_USER: building-service
  MONGO_PASSWORD: Hgp5P5Mw9Q1wfhpgS26R
  MONGO_HOST: database
  PORT: "3000"
type: Opaque

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: building
  namespace: dev
  labels:
    app: building
spec:
  tls:
    - hosts:
        - testing.devopsapp.ngaxavilabs.com
      secretName: testing-devopsapp-ngaxavilabs-com-tls
  rules:
    - host: testing.devopsapp.ngaxavilabs.com
      http:
        paths:
          - backend:
              serviceName: building
              servicePort: 3000
            path: /api/buildings
